@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class CommentCommandParser {
  +parse(): CommentCommand
}

Class Parser
Class ParserException

CommentCommandParser .up.|> Parser
CommentCommandParser ..> CommentCommand : <<create>>
CommentCommandParser .right.> ParserException: throws >
@enduml
