@startuml
hide circle
skinparam classAttributeIconSize 0

Class "<<interface>>\nParser<T extends Command>" as Parser {
  +parse(String): T
}
Class CommentCommandParser {
  +parse(String): CommentCommand
}
Class ParseException

CommentCommandParser .up.|> Parser : T = CommentCommand
CommentCommandParser ..> CommentCommand : <<create>>
Parser .right.> ParseException: throws >
CommentCommandParser .right.> ParseException: throws >
@enduml
